#!/bin/sh
# Build the TypeScript config and launch Neovim with it, fully isolated from
# ~/.config/nvim (own XDG dirs live under ./.nvim so plugins/state stay local).
set -e
ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
npx tstl
mkdir -p .nvim/config/nvim .nvim/data .nvim/state .nvim/cache
cat > .nvim/config/nvim/init.lua <<LUA
-- generated by nvim.sh: delegates to the TypeScript-compiled config
package.path = "$ROOT/dist/?.lua;" .. package.path
dofile("$ROOT/dist/init.lua")
LUA
XDG_CONFIG_HOME="$ROOT/.nvim/config" \
XDG_DATA_HOME="$ROOT/.nvim/data" \
XDG_STATE_HOME="$ROOT/.nvim/state" \
XDG_CACHE_HOME="$ROOT/.nvim/cache" \
exec nvim "$@"
